src/main/java/infobalt/robusta/entities/Assignment.java
package infobalt.robusta.entities;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
public class Assignment {

	@Id
	@GeneratedValue
	private Long id;
	private String name;
	
	//@ManyToOne (optional = true, fetch = FetchType.EAGER, cascade = {CascadeType.MERGE})
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "train_id")
	private Project project;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Override
	public String toString() {
		return ("vehicle id: " + id + " name: " + name);
	}
	
}

src/main/java/infobalt/robusta/entities/Project.java
package infobalt.robusta.entities;

import java.util.Date;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Project {

	@Id
	@GeneratedValue
	private Long id;

	private String name;

	@Temporal(TemporalType.DATE)
	private Date startDate;

	private String manager;

	@OneToMany(mappedBy = "project", orphanRemoval = true, fetch = FetchType.EAGER) //, cascade = { CascadeType.ALL }
	private List<Assignment> assignments;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public List<Assignment> getAssignments() {
		return assignments;
	}

	public void setAssignments(List<Assignment> assignments) {
		this.assignments = assignments;
	}

	

}

src/main/java/infobalt/robusta/ui/controllers/AssignmentListPageBean.java
package infobalt.robusta.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import infobalt.robusta.entities.Assignment;
import infobalt.robusta.entities.Project;
import infobalt.robusta.repositories.AssignmentRepository;
import infobalt.robusta.repositories.ProjectRepository;
import infobalt.robusta.ui.controllers.ProjectListPageBean.ProjectListPageData;

/**
 * This class is the Invoice list page controller. It deals with user commands and
 * navigation. Scope: request
 *
 */
public class AssignmentListPageBean implements Serializable { // this is the Controller
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -1389684115871062390L;

	static final Logger log = LoggerFactory.getLogger(AssignmentListPageBean.class);
	
	public static final String NAV_LIST_PROJECTS = "list-projects";
	public static final String NAV_UPDATE_PROJECT = "update-project";
	
	/**
	 * this class holds data in session and does nothing else whatsoever; scope: session
	 */
	public static class AssignmentListPageData implements Serializable {  // this is the Model

		/**
		 * 
		 */
		private static final long serialVersionUID = -8131673305859876205L;

		@Valid
		private Assignment currentAssignment;
		
		public void init() {
			currentAssignment = new Assignment();
		}

		public Assignment getCurrentAssignment() {
			return currentAssignment;
		}

		public void setCurrentAssignment(Assignment currentAssignment) {
			this.currentAssignment = currentAssignment;
		}
	}

	private ProjectRepository projectRepo;				// singleton
	private ProjectListPageData projectListPageData;	// model: session scope
	private ProjectListPageBean projectListPage;	// controller: request scope
	private AssignmentRepository assignmentRepo;			// singleton
	private AssignmentListPageData assignmentListPageData;// model: session scope


	public String addNewAssignment(Project currentProject) {
		assignmentListPageData.setCurrentAssignment(new Assignment());
		projectListPageData.setCurrentProject(currentProject);
		return ProjectListPageBean.NAV_UPDATE_ASSIGNMENTS;
	}
	
	public String update(Assignment assignment) {
		assignmentListPageData.setCurrentAssignment(assignment);
		return ProjectListPageBean.NAV_UPDATE_ASSIGNMENTS;
	}
	
	public String save() {
		assignmentListPageData.getCurrentAssignment().setProject(projectListPageData.getCurrentProject());
		assignmentRepo.save(assignmentListPageData.getCurrentAssignment());
		assignmentListPageData.setCurrentAssignment(new Assignment());
		return ProjectListPageBean.NAV_UPDATE_ASSIGNMENTS;
	}
	
	public String delete(Assignment assignment) {
		assignmentRepo.delete(assignment);
		return ProjectListPageBean.NAV_UPDATE_ASSIGNMENTS;
	}
	
	public String cancel() {
		assignmentListPageData.setCurrentAssignment(new Assignment());
		return ProjectListPageBean.NAV_UPDATE_ASSIGNMENTS;
	}
	
	public List<Assignment> findAssignmentsByProject() {
		return assignmentRepo.findAllByProject(projectListPage.getProjectListPageData().getCurrentProject());
	}

	public ProjectListPageData getProjectListPageData() {
		return projectListPageData;
	}
	public void setProjectListPageData(ProjectListPageData projectListPageData) {
		this.projectListPageData = projectListPageData;
	}
	public AssignmentListPageData getAssignmentListPageData() {
		return assignmentListPageData;
	}
	public void setAssignmentListPageData(AssignmentListPageData assignmentListPageData) {
		this.assignmentListPageData = assignmentListPageData;
	}

	public ProjectRepository getProjectRepo() {
		return projectRepo;
	}

	public void setProjectRepo(ProjectRepository projectRepo) {
		this.projectRepo = projectRepo;
	}

	public ProjectListPageBean getProjectListPage() {
		return projectListPage;
	}

	public void setProjectListPage(ProjectListPageBean projectListPage) {
		this.projectListPage = projectListPage;
	}

	public AssignmentRepository getAssignmentRepo() {
		return assignmentRepo;
	}

	public void setAssignmentRepo(AssignmentRepository assignmentRepo) {
		this.assignmentRepo = assignmentRepo;
	}

	
}

src/main/java/infobalt/robusta/ui/controllers/ProjectListPageBean.java
package infobalt.robusta.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import infobalt.robusta.entities.Assignment;
import infobalt.robusta.entities.Project;
import infobalt.robusta.repositories.ProjectRepository;

/**
 * This class is the Invoice list page controller. It deals with user commands
 * and navigation
 *
 */
public class ProjectListPageBean implements Serializable { // this is the
															// Controller,
															// scope: request

	/**
	 * 
	 */
	private static final long serialVersionUID = -8143077418240345336L;

	static final Logger log = LoggerFactory.getLogger(ProjectListPageBean.class);

	public static final String NAV_LIST_PROJECTS = "list-projects";
	public static final String NAV_UPDATE_PROJECT = "update-project";
	public static final String NAV_UPDATE_ASSIGNMENTS = "update-assignments";

	/**
	 * this class holds data in session
	 */
	public static class ProjectListPageData implements Serializable { // this is
																	// the
																	// Model,
																	// scope:
																	// session

		/**
		 * 
		 */
		private static final long serialVersionUID = 5040310448257955354L;

		@Valid
		private Project currentProject;

		public void init() {
			currentProject = new Project();
		}

		public Project getCurrentProject() {
			return currentProject;
		}

		public void setCurrentProject(Project currentProject) {
			this.currentProject = currentProject;
		}

	}

	private ProjectListPageData projectListPageData; // the model, session scope
	private ProjectRepository projectRepo; // singleton

	public String create() {
		projectListPageData.setCurrentProject(new Project());
		return NAV_LIST_PROJECTS;
	}

	public String delete(Project project) {
		projectRepo.delete(project);
		return NAV_LIST_PROJECTS;
	}

	public List<Project> getProjectList() {
		return projectRepo.findAll();
	}
	
	public List<Assignment> findAssignmentsByProject() {
		return projectListPageData.getCurrentProject().getAssignments();
	}
	
	public List<Assignment> getFreshAssignmentList() {
		return projectRepo.findById(projectListPageData.getCurrentProject().getId()).getAssignments();
	}

	public String update(Project project) {
		projectListPageData.setCurrentProject(project);
		return NAV_UPDATE_PROJECT;
	}

	public String save() {
		projectRepo.save(projectListPageData.getCurrentProject());
		return NAV_LIST_PROJECTS;
	}
	
	public String cancel() {
		projectListPageData.setCurrentProject(new Project());
		return NAV_LIST_PROJECTS;
	}

	public ProjectListPageData getProjectListPageData() {
		return projectListPageData;
	}

	public void setProjectListPageData(ProjectListPageData projectListPageData) {
		this.projectListPageData = projectListPageData;
	}

	public ProjectRepository getProjectRepo() {
		return projectRepo;
	}

	public void setProjectRepo(ProjectRepository projectRepo) {
		this.projectRepo = projectRepo;
	}

}

src/main/webapp/addOrRemoveAssignments.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="turinys">
		<h:form>

			<p:growl id="growl" showDetail="true" sticky="false" />

			<p:panelGrid columns="2">
				<h:outputText value="Current project ID:" />
				<h:outputText value="#{projectListPageData.currentProject.id}" />

				<h:outputText value="Serial number:" />
				<h:outputText value="#{projectListPageData.currentProject.name}" />

				<h:outputText value="Maker:" />
				<h:outputText value="#{projectListPageData.currentProject.manager}" />

				<h:outputText value="Make date:" />
				<h:outputText value="#{projectListPageData.currentProject.startDate}" />
			</p:panelGrid>
		</h:form>
		<h:form>
			<p:dataTable id="assignmentTable"
				value="#{projectListPage.getFreshAssignmentList()}" var="assignment">
				<p:column headerText="Id">
					<h:outputText value="#{assignment.id}" />
				</p:column>

				<p:column headerText="Name">
					<h:outputText value="#{assignment.name}" />
				</p:column>

				<p:column headerText="">
					<p:commandButton value="Delete" update="@form" immediate="true"
						actionListener="#{assignmentListPage.delete(assignment)}">
						<p:confirm header="Confirmation" message="Are you sure?"
							icon="ui-icon-alert" />
					</p:commandButton>
					<p:commandButton value="Update"
						action="#{assignmentListPage.update(assignment)}" />
					<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
						<p:commandButton value="Yes" type="button"
							styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
						<p:commandButton value="No" type="button"
							styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
					</p:confirmDialog>
				</p:column>
			</p:dataTable>


			<p:panel id="basicAssignment" header="New assignment">
				<h:panelGrid id="grid2" columns="3" cellpadding="5">
					<h:outputLabel for="assignment_name" value="Assignment name"></h:outputLabel>
					<h:inputText id="assignment_name"
						value="#{assignmentListPageData.currentAssignment.name}">
						<f:validateBean />
					</h:inputText>
					<p:growl for="assignment_name" display="icon" />
				</h:panelGrid>
			</p:panel>

			<p:commandButton action="addOrRemoveAssignments"
				actionListener="#{assignmentListPage.save()}"
				update="@form" value="Add new assignment">
			</p:commandButton>
			<p:commandButton actionListener="#{assignmentListPage.cancel()}"
				action="projects" value="Cancel">
			</p:commandButton>
		</h:form>
	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add or remove assignments on selected project
 	 </ui:define>

</ui:composition>

src/main/webapp/addOrUpdateProject.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="turinys">
		<h:form>

			<p:growl id="growl" showDetail="true" sticky="false" />

			<p:panelGrid columns="2">
				<h:outputText value="Project ID:" />
				<h:outputText value="#{projectListPageData.currentProject.id}" />

				<h:outputText value="Project name:" />
				<h:outputText value="#{projectListPageData.currentProject.name}" />

				<h:outputText value="Maker:" />
				<h:outputText value="#{projectListPageData.currentProject.manager}" />

				<h:outputText value="Make date:" />
				<h:outputText value="#{projectListPageData.currentProject.startDate}" />
			</p:panelGrid>
		</h:form>
		<h:form>
			<p:panel id="basic" header="Enter project details">
				<h:panelGrid id="grid1" columns="3" cellpadding="5">
					<h:outputLabel for="project_name" value="Project name"></h:outputLabel>
					<p:inputText id="project_name"
						value="#{projectListPageData.currentProject.name}">
						<f:validateBean />
					</p:inputText>
					<p:growl for="project_name" display="icon" />

					<h:outputLabel for="project_manager" value="Project manager"></h:outputLabel>
					<p:inputText id="project_manager"
						value="#{projectListPageData.currentProject.manager}"></p:inputText>
					<p:growl for="project_manager" display="icon" />

					<h:outputLabel for="project_startdate" value="Start date"></h:outputLabel>
					<p:calendar id="project_startdate"
						value="#{projectListPageData.currentProject.startDate}"
						pattern="yyyy-MM-dd"></p:calendar>
					<p:growl for="project_startdate" display="icon" />

				</h:panelGrid>

			</p:panel>

			<h:commandButton actionListener="#{projectListPage.save()}"
				action="projects" value="Save project details">
			</h:commandButton>
			<h:commandButton actionListener="#{projectListPage.cancel()}"
				action="projects" value="Cancel">
			</h:commandButton>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add or update project
 	 </ui:define>

</ui:composition>

src/main/webapp/footer.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head></h:head>
<h:body>
	<ui:composition>

		<div id="logo"></div>

	</ui:composition>
</h:body>
</h:html>

src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>Project management: <ui:insert name="pavadinimas">
  		No title
  	</ui:insert>
	</title>
	<h:outputStylesheet name="style.css"></h:outputStylesheet>
</h:head>
<h:body>
	<div id="container">
		<h:form>
			<p:tabMenu activeIndex="#{param.i}">
				<p:menuitem value="Project list" outcome="list-projects"
					icon="ui-icon-search">
					<f:param name="i" value="0" />
				</p:menuitem>
				<p:menuitem value="Add or edit project" outcome="update-project"
					icon="ui-icon-wrench">
					<f:param name="i" value="1" />
				</p:menuitem>
			</p:tabMenu>
		</h:form>
		<div id="contents">
			<ui:insert name="turinys">
		  		No content
		  	</ui:insert>
		</div>
	</div>
	<div id="footer-container">
		<div id="footer">
			<ui:insert name="footer">
				<ui:include src="footer.xhtml" />
			</ui:insert>
		</div>
	</div>
</h:body>
</html>

src/main/webapp/projects.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="turinys">
		<h:form>

			<p:growl id="growl" showDetail="true" sticky="false" />

			<p:dataTable value="#{projectListPage.projectList}" var="project">
				<p:column headerText="Id">
					<h:outputText value="#{project.id}" />
				</p:column>

				<p:column headerText="Serial">
					<h:outputText value="#{project.name}" />
				</p:column>

				<p:column headerText="Maker">
					<h:outputText value="#{project.manager}" />
				</p:column>

				<p:column headerText="Make date">
					<h:outputText value="#{project.startDate}" />
				</p:column>

				<p:column headerText="Select a project:">
					<p:commandButton value="Manage assignments"
						action="addOrRemoveAssignments"
						actionListener="#{assignmentListPage.addNewAssignment(project)}">
					</p:commandButton>
					<p:commandButton value="Edit info"
						action="#{projectListPage.update(project)}">
					</p:commandButton>
					<p:commandButton value="Delete project"
						action="#{projectListPage.delete(project)}">
						<p:confirm header="Confirmation" message="Are you sure?"
							icon="ui-icon-alert" />
					</p:commandButton>
					<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
						<p:commandButton value="Yes" type="button"
							styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
						<p:commandButton value="No" type="button"
							styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
					</p:confirmDialog>
				</p:column>
			</p:dataTable>
			<p:commandButton action="addOrUpdateProject"
				actionListener="#{projectListPage.create()}" update="@form"
				value="Create new project" />

		</h:form>

		<f:facet name="header">
			<p:graphicImage name="infundibulogo.png" />
		</f:facet>
	</ui:define>

	<ui:define name="pavadinimas">
 	 	All projects
 	 </ui:define>

</ui:composition>